import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar ,{NavItem} from "./components/navBar";
import Footer from "./components/Footer";
import WrapComponent from "./components/wrapComponent";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WrapComponent >
        <NavBar >
           <NavItem href="/" index={0} name='Home' />
           <NavItem href="/Courses" index={1} name='Courses' />
           <NavItem href="/" index={2} name='Contacts' />
          </NavBar>
         
            {children}

        </WrapComponent>
        
       

         
        <Footer />
       
      </body>
    </html>
  );
}
